name: Build

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x86_64
            cmake_arch_flag: ""
          - os: macos-latest
            arch: arm64
            cmake_arch_flag: "-DCMAKE_OSX_ARCHITECTURES=arm64"
          - os: macos-14
            arch: x86_64
            cmake_arch_flag: "-DCMAKE_OSX_ARCHITECTURES=x86_64"
          - os: ubuntu-latest
            arch: x86_64
            cmake_arch_flag: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive


      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756

      - name: Set up sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmake_arch_flag }} -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build
        run: cmake --build build --config Release --target reaper_aaf

      - name: Strip debug symbols (macOS)
        if: runner.os == 'macOS'
        run: strip -x build/reaper_reAAF.dylib

      - name: Strip debug symbols (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: strip build/reaper_reAAF.so

      - name: Upload artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: reaper-aaf-windows-x86_64
          path: build/Release/reaper_reAAF.dll

      - name: Upload artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: reaper-aaf-macos-${{ matrix.arch }}
          path: build/reaper_reAAF.dylib

      - name: Upload artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: reaper-aaf-linux-x86_64
          path: build/reaper_reAAF.so
